// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYMXrkyXA6VyUY_1g1iDsOHAoCa4mHjM',
    appId: '1:672589613346:web:9374cfe9799331c65e7d7b',
    messagingSenderId: '672589613346',
    projectId: 'graduation-project-5467a',
    authDomain: 'graduation-project-5467a.firebaseapp.com',
    storageBucket: 'graduation-project-5467a.firebasestorage.app',
    measurementId: 'G-C6100HQ36V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXBAB0nzqnSOfwvDX5we2WP5pbrqDWYd0',
    appId: '1:672589613346:android:4c025a1926cee4df5e7d7b',
    messagingSenderId: '672589613346',
    projectId: 'graduation-project-5467a',
    storageBucket: 'graduation-project-5467a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1lzQbkNQAQkw0FximGIj3FUvk0V2PeU',
    appId: '1:672589613346:ios:6c2a9d1c86da6c7c5e7d7b',
    messagingSenderId: '672589613346',
    projectId: 'graduation-project-5467a',
    storageBucket: 'graduation-project-5467a.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

}